name: lemon_squeezy
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  collection: ">=1.18.0 <2.0.0"
  equatable: ">=2.0.5 <3.0.0"
  json_annotation: ^4.9.0
  chopper: ^8.0.1+1
  http: ">=1.2.2 <2.0.0"
  logging: ^1.3.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.8
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  chopper_generator: ^8.0.3

